/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BoostRouteImport } from './routes/boost'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as HubRouteImport } from './routes/hub'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademyAttendanceRouteImport } from './routes/academy.attendance'
import { Route as AcademyGradesRouteImport } from './routes/academy.grades'
import { Route as AcademyManageRouteImport } from './routes/academy.manage'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsInventoryRouteImport } from './routes/assets.inventory'
import { Route as BoostIndexRouteImport } from './routes/boost.index'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskCategoriesRouteImport } from './routes/desk.categories'
import { Route as DeskTeamRouteImport } from './routes/desk.team'
import { Route as DeskTicketsRouteImport } from './routes/desk.tickets'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as FinanceBoletosRouteImport } from './routes/finance.boletos'
import { Route as FinanceChargesRouteImport } from './routes/finance.charges'
import { Route as FinanceDiscountsRouteImport } from './routes/finance.discounts'
import { Route as FinanceManageRouteImport } from './routes/finance.manage'
import { Route as FinanceNfeRouteImport } from './routes/finance.nfe'
import { Route as FinanceProductsRouteImport } from './routes/finance.products'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as FinanceServicesRouteImport } from './routes/finance.services'
import { Route as FinanceSettingsRouteImport } from './routes/finance.settings'
import { Route as FinanceTuitionsRouteImport } from './routes/finance.tuitions'
import { Route as HubIndexRouteImport } from './routes/hub.index'
import { Route as HubAcessosRouteImport } from './routes/hub.acessos'
import { Route as HubSetoresRouteImport } from './routes/hub.setores'
import { Route as HubUsuariosRouteImport } from './routes/hub.usuarios'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnClassesRouteImport } from './routes/learn.classes'
import { Route as LearnStudentRouteImport } from './routes/learn.student'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsBookRouteImport } from './routes/rooms.book'
import { Route as RoomsReservationsRouteImport } from './routes/rooms.reservations'
import { Route as RoomsStructureRouteImport } from './routes/rooms.structure'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentActivitiesRouteImport } from './routes/student.activities'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentCalendarRouteImport } from './routes/student.calendar'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentDisciplinesRouteImport } from './routes/student.disciplines'
import { Route as StudentDocumentsRouteImport } from './routes/student.documents'
import { Route as StudentFinanceRouteImport } from './routes/student.finance'
import { Route as StudentGradesRouteImport } from './routes/student.grades'
import { Route as StudentHistoryRouteImport } from './routes/student.history'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentReservationsRouteImport } from './routes/student.reservations'
import { Route as StudentTicketsRouteImport } from './routes/student.tickets'
import { Route as BoostCoursesIdRouteImport } from './routes/boost.courses.$id'
import { Route as DeskCategoriesIndexRouteImport } from './routes/desk.categories.index'
import { Route as DeskCategoriesIdRouteImport } from './routes/desk.categories.$id'
import { Route as DeskTicketsIdRouteImport } from './routes/desk.tickets.$id'
import { Route as LearnActivitiesIdRouteImport } from './routes/learn.activities.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostRoute = BoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyAttendanceRoute = AcademyAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyGradesRoute = AcademyGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyManageRoute = AcademyManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AcademyRoute,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsInventoryRoute = AssetsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AssetsRoute,
} as any)
const BoostIndexRoute = BoostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoostRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskCategoriesRoute = DeskCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTeamRoute = DeskTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTicketsRoute = DeskTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DeskRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceBoletosRoute = FinanceBoletosRouteImport.update({
  id: '/boletos',
  path: '/boletos',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceChargesRoute = FinanceChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceDiscountsRoute = FinanceDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceManageRoute = FinanceManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceNfeRoute = FinanceNfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceProductsRoute = FinanceProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceServicesRoute = FinanceServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceSettingsRoute = FinanceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceTuitionsRoute = FinanceTuitionsRouteImport.update({
  id: '/tuitions',
  path: '/tuitions',
  getParentRoute: () => FinanceRoute,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRoute,
} as any)
const HubAcessosRoute = HubAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => HubRoute,
} as any)
const HubSetoresRoute = HubSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => HubRoute,
} as any)
const HubUsuariosRoute = HubUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => HubRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnClassesRoute = LearnClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => LearnRoute,
} as any)
const LearnStudentRoute = LearnStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => LearnRoute,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsBookRoute = RoomsBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsReservationsRoute = RoomsReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsStructureRoute = RoomsStructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => RoomsRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentActivitiesRoute = StudentActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDisciplinesRoute = StudentDisciplinesRouteImport.update({
  id: '/disciplines',
  path: '/disciplines',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDocumentsRoute = StudentDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFinanceRoute = StudentFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHistoryRoute = StudentHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentReservationsRoute = StudentReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTicketsRoute = StudentTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => StudentRoute,
} as any)
const BoostCoursesIdRoute = BoostCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => BoostRoute,
} as any)
const DeskCategoriesIndexRoute = DeskCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskCategoriesRoute,
} as any)
const DeskCategoriesIdRoute = DeskCategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeskCategoriesRoute,
} as any)
const DeskTicketsIdRoute = DeskTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeskTicketsRoute,
} as any)
const LearnActivitiesIdRoute = LearnActivitiesIdRouteImport.update({
  id: '/activities/$id',
  path: '/activities/$id',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/assets': typeof AssetsRouteWithChildren
  '/boost': typeof BoostRouteWithChildren
  '/desk': typeof DeskRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/hub': typeof HubRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRouteWithChildren
  '/academy/attendance': typeof AcademyAttendanceRoute
  '/academy/grades': typeof AcademyGradesRoute
  '/academy/manage': typeof AcademyManageRoute
  '/assets/inventory': typeof AssetsInventoryRoute
  '/desk/categories': typeof DeskCategoriesRouteWithChildren
  '/desk/team': typeof DeskTeamRoute
  '/desk/tickets': typeof DeskTicketsRouteWithChildren
  '/finance/boletos': typeof FinanceBoletosRoute
  '/finance/charges': typeof FinanceChargesRoute
  '/finance/discounts': typeof FinanceDiscountsRoute
  '/finance/manage': typeof FinanceManageRoute
  '/finance/nfe': typeof FinanceNfeRoute
  '/finance/products': typeof FinanceProductsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/services': typeof FinanceServicesRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/tuitions': typeof FinanceTuitionsRoute
  '/hub/acessos': typeof HubAcessosRoute
  '/hub/setores': typeof HubSetoresRoute
  '/hub/usuarios': typeof HubUsuariosRoute
  '/learn/classes': typeof LearnClassesRoute
  '/learn/student': typeof LearnStudentRoute
  '/rooms/book': typeof RoomsBookRoute
  '/rooms/reservations': typeof RoomsReservationsRoute
  '/rooms/structure': typeof RoomsStructureRoute
  '/student/activities': typeof StudentActivitiesRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/disciplines': typeof StudentDisciplinesRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/finance': typeof StudentFinanceRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/reservations': typeof StudentReservationsRoute
  '/student/tickets': typeof StudentTicketsRoute
  '/academy/': typeof AcademyIndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/boost/': typeof BoostIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/hub/': typeof HubIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/student/': typeof StudentIndexRoute
  '/boost/courses/$id': typeof BoostCoursesIdRoute
  '/desk/categories/$id': typeof DeskCategoriesIdRoute
  '/desk/tickets/$id': typeof DeskTicketsIdRoute
  '/learn/activities/$id': typeof LearnActivitiesIdRoute
  '/desk/categories/': typeof DeskCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/academy/attendance': typeof AcademyAttendanceRoute
  '/academy/grades': typeof AcademyGradesRoute
  '/academy/manage': typeof AcademyManageRoute
  '/assets/inventory': typeof AssetsInventoryRoute
  '/desk/team': typeof DeskTeamRoute
  '/desk/tickets': typeof DeskTicketsRouteWithChildren
  '/finance/boletos': typeof FinanceBoletosRoute
  '/finance/charges': typeof FinanceChargesRoute
  '/finance/discounts': typeof FinanceDiscountsRoute
  '/finance/manage': typeof FinanceManageRoute
  '/finance/nfe': typeof FinanceNfeRoute
  '/finance/products': typeof FinanceProductsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/services': typeof FinanceServicesRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/tuitions': typeof FinanceTuitionsRoute
  '/hub/acessos': typeof HubAcessosRoute
  '/hub/setores': typeof HubSetoresRoute
  '/hub/usuarios': typeof HubUsuariosRoute
  '/learn/classes': typeof LearnClassesRoute
  '/learn/student': typeof LearnStudentRoute
  '/rooms/book': typeof RoomsBookRoute
  '/rooms/reservations': typeof RoomsReservationsRoute
  '/rooms/structure': typeof RoomsStructureRoute
  '/student/activities': typeof StudentActivitiesRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/disciplines': typeof StudentDisciplinesRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/finance': typeof StudentFinanceRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/reservations': typeof StudentReservationsRoute
  '/student/tickets': typeof StudentTicketsRoute
  '/academy': typeof AcademyIndexRoute
  '/assets': typeof AssetsIndexRoute
  '/boost': typeof BoostIndexRoute
  '/desk': typeof DeskIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/hub': typeof HubIndexRoute
  '/learn': typeof LearnIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/student': typeof StudentIndexRoute
  '/boost/courses/$id': typeof BoostCoursesIdRoute
  '/desk/categories/$id': typeof DeskCategoriesIdRoute
  '/desk/tickets/$id': typeof DeskTicketsIdRoute
  '/learn/activities/$id': typeof LearnActivitiesIdRoute
  '/desk/categories': typeof DeskCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/assets': typeof AssetsRouteWithChildren
  '/boost': typeof BoostRouteWithChildren
  '/desk': typeof DeskRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/hub': typeof HubRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRouteWithChildren
  '/academy/attendance': typeof AcademyAttendanceRoute
  '/academy/grades': typeof AcademyGradesRoute
  '/academy/manage': typeof AcademyManageRoute
  '/assets/inventory': typeof AssetsInventoryRoute
  '/desk/categories': typeof DeskCategoriesRouteWithChildren
  '/desk/team': typeof DeskTeamRoute
  '/desk/tickets': typeof DeskTicketsRouteWithChildren
  '/finance/boletos': typeof FinanceBoletosRoute
  '/finance/charges': typeof FinanceChargesRoute
  '/finance/discounts': typeof FinanceDiscountsRoute
  '/finance/manage': typeof FinanceManageRoute
  '/finance/nfe': typeof FinanceNfeRoute
  '/finance/products': typeof FinanceProductsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/services': typeof FinanceServicesRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/tuitions': typeof FinanceTuitionsRoute
  '/hub/acessos': typeof HubAcessosRoute
  '/hub/setores': typeof HubSetoresRoute
  '/hub/usuarios': typeof HubUsuariosRoute
  '/learn/classes': typeof LearnClassesRoute
  '/learn/student': typeof LearnStudentRoute
  '/rooms/book': typeof RoomsBookRoute
  '/rooms/reservations': typeof RoomsReservationsRoute
  '/rooms/structure': typeof RoomsStructureRoute
  '/student/activities': typeof StudentActivitiesRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/disciplines': typeof StudentDisciplinesRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/finance': typeof StudentFinanceRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/reservations': typeof StudentReservationsRoute
  '/student/tickets': typeof StudentTicketsRoute
  '/academy/': typeof AcademyIndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/boost/': typeof BoostIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/hub/': typeof HubIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/student/': typeof StudentIndexRoute
  '/boost/courses/$id': typeof BoostCoursesIdRoute
  '/desk/categories/$id': typeof DeskCategoriesIdRoute
  '/desk/tickets/$id': typeof DeskTicketsIdRoute
  '/learn/activities/$id': typeof LearnActivitiesIdRoute
  '/desk/categories/': typeof DeskCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/assets'
    | '/boost'
    | '/desk'
    | '/finance'
    | '/hub'
    | '/learn'
    | '/login'
    | '/rooms'
    | '/settings'
    | '/student'
    | '/academy/attendance'
    | '/academy/grades'
    | '/academy/manage'
    | '/assets/inventory'
    | '/desk/categories'
    | '/desk/team'
    | '/desk/tickets'
    | '/finance/boletos'
    | '/finance/charges'
    | '/finance/discounts'
    | '/finance/manage'
    | '/finance/nfe'
    | '/finance/products'
    | '/finance/reports'
    | '/finance/services'
    | '/finance/settings'
    | '/finance/tuitions'
    | '/hub/acessos'
    | '/hub/setores'
    | '/hub/usuarios'
    | '/learn/classes'
    | '/learn/student'
    | '/rooms/book'
    | '/rooms/reservations'
    | '/rooms/structure'
    | '/student/activities'
    | '/student/attendance'
    | '/student/calendar'
    | '/student/courses'
    | '/student/disciplines'
    | '/student/documents'
    | '/student/finance'
    | '/student/grades'
    | '/student/history'
    | '/student/notifications'
    | '/student/profile'
    | '/student/reservations'
    | '/student/tickets'
    | '/academy/'
    | '/assets/'
    | '/boost/'
    | '/desk/'
    | '/finance/'
    | '/hub/'
    | '/learn/'
    | '/rooms/'
    | '/student/'
    | '/boost/courses/$id'
    | '/desk/categories/$id'
    | '/desk/tickets/$id'
    | '/learn/activities/$id'
    | '/desk/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/academy/attendance'
    | '/academy/grades'
    | '/academy/manage'
    | '/assets/inventory'
    | '/desk/team'
    | '/desk/tickets'
    | '/finance/boletos'
    | '/finance/charges'
    | '/finance/discounts'
    | '/finance/manage'
    | '/finance/nfe'
    | '/finance/products'
    | '/finance/reports'
    | '/finance/services'
    | '/finance/settings'
    | '/finance/tuitions'
    | '/hub/acessos'
    | '/hub/setores'
    | '/hub/usuarios'
    | '/learn/classes'
    | '/learn/student'
    | '/rooms/book'
    | '/rooms/reservations'
    | '/rooms/structure'
    | '/student/activities'
    | '/student/attendance'
    | '/student/calendar'
    | '/student/courses'
    | '/student/disciplines'
    | '/student/documents'
    | '/student/finance'
    | '/student/grades'
    | '/student/history'
    | '/student/notifications'
    | '/student/profile'
    | '/student/reservations'
    | '/student/tickets'
    | '/academy'
    | '/assets'
    | '/boost'
    | '/desk'
    | '/finance'
    | '/hub'
    | '/learn'
    | '/rooms'
    | '/student'
    | '/boost/courses/$id'
    | '/desk/categories/$id'
    | '/desk/tickets/$id'
    | '/learn/activities/$id'
    | '/desk/categories'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/assets'
    | '/boost'
    | '/desk'
    | '/finance'
    | '/hub'
    | '/learn'
    | '/login'
    | '/rooms'
    | '/settings'
    | '/student'
    | '/academy/attendance'
    | '/academy/grades'
    | '/academy/manage'
    | '/assets/inventory'
    | '/desk/categories'
    | '/desk/team'
    | '/desk/tickets'
    | '/finance/boletos'
    | '/finance/charges'
    | '/finance/discounts'
    | '/finance/manage'
    | '/finance/nfe'
    | '/finance/products'
    | '/finance/reports'
    | '/finance/services'
    | '/finance/settings'
    | '/finance/tuitions'
    | '/hub/acessos'
    | '/hub/setores'
    | '/hub/usuarios'
    | '/learn/classes'
    | '/learn/student'
    | '/rooms/book'
    | '/rooms/reservations'
    | '/rooms/structure'
    | '/student/activities'
    | '/student/attendance'
    | '/student/calendar'
    | '/student/courses'
    | '/student/disciplines'
    | '/student/documents'
    | '/student/finance'
    | '/student/grades'
    | '/student/history'
    | '/student/notifications'
    | '/student/profile'
    | '/student/reservations'
    | '/student/tickets'
    | '/academy/'
    | '/assets/'
    | '/boost/'
    | '/desk/'
    | '/finance/'
    | '/hub/'
    | '/learn/'
    | '/rooms/'
    | '/student/'
    | '/boost/courses/$id'
    | '/desk/categories/$id'
    | '/desk/tickets/$id'
    | '/learn/activities/$id'
    | '/desk/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AssetsRoute: typeof AssetsRouteWithChildren
  BoostRoute: typeof BoostRouteWithChildren
  DeskRoute: typeof DeskRouteWithChildren
  FinanceRoute: typeof FinanceRouteWithChildren
  HubRoute: typeof HubRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost': {
      id: '/boost'
      path: '/boost'
      fullPath: '/boost'
      preLoaderRoute: typeof BoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/attendance': {
      id: '/academy/attendance'
      path: '/attendance'
      fullPath: '/academy/attendance'
      preLoaderRoute: typeof AcademyAttendanceRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/grades': {
      id: '/academy/grades'
      path: '/grades'
      fullPath: '/academy/grades'
      preLoaderRoute: typeof AcademyGradesRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/manage': {
      id: '/academy/manage'
      path: '/manage'
      fullPath: '/academy/manage'
      preLoaderRoute: typeof AcademyManageRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/assets/': {
      id: '/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/inventory': {
      id: '/assets/inventory'
      path: '/inventory'
      fullPath: '/assets/inventory'
      preLoaderRoute: typeof AssetsInventoryRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/boost/': {
      id: '/boost/'
      path: '/'
      fullPath: '/boost/'
      preLoaderRoute: typeof BoostIndexRouteImport
      parentRoute: typeof BoostRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/categories': {
      id: '/desk/categories'
      path: '/categories'
      fullPath: '/desk/categories'
      preLoaderRoute: typeof DeskCategoriesRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/team': {
      id: '/desk/team'
      path: '/team'
      fullPath: '/desk/team'
      preLoaderRoute: typeof DeskTeamRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/tickets': {
      id: '/desk/tickets'
      path: '/tickets'
      fullPath: '/desk/tickets'
      preLoaderRoute: typeof DeskTicketsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/boletos': {
      id: '/finance/boletos'
      path: '/boletos'
      fullPath: '/finance/boletos'
      preLoaderRoute: typeof FinanceBoletosRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/charges': {
      id: '/finance/charges'
      path: '/charges'
      fullPath: '/finance/charges'
      preLoaderRoute: typeof FinanceChargesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/discounts': {
      id: '/finance/discounts'
      path: '/discounts'
      fullPath: '/finance/discounts'
      preLoaderRoute: typeof FinanceDiscountsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/manage': {
      id: '/finance/manage'
      path: '/manage'
      fullPath: '/finance/manage'
      preLoaderRoute: typeof FinanceManageRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/nfe': {
      id: '/finance/nfe'
      path: '/nfe'
      fullPath: '/finance/nfe'
      preLoaderRoute: typeof FinanceNfeRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/products': {
      id: '/finance/products'
      path: '/products'
      fullPath: '/finance/products'
      preLoaderRoute: typeof FinanceProductsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/services': {
      id: '/finance/services'
      path: '/services'
      fullPath: '/finance/services'
      preLoaderRoute: typeof FinanceServicesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/settings': {
      id: '/finance/settings'
      path: '/settings'
      fullPath: '/finance/settings'
      preLoaderRoute: typeof FinanceSettingsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/tuitions': {
      id: '/finance/tuitions'
      path: '/tuitions'
      fullPath: '/finance/tuitions'
      preLoaderRoute: typeof FinanceTuitionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/hub/': {
      id: '/hub/'
      path: '/'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/acessos': {
      id: '/hub/acessos'
      path: '/acessos'
      fullPath: '/hub/acessos'
      preLoaderRoute: typeof HubAcessosRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/setores': {
      id: '/hub/setores'
      path: '/setores'
      fullPath: '/hub/setores'
      preLoaderRoute: typeof HubSetoresRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/usuarios': {
      id: '/hub/usuarios'
      path: '/usuarios'
      fullPath: '/hub/usuarios'
      preLoaderRoute: typeof HubUsuariosRouteImport
      parentRoute: typeof HubRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/classes': {
      id: '/learn/classes'
      path: '/classes'
      fullPath: '/learn/classes'
      preLoaderRoute: typeof LearnClassesRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/student': {
      id: '/learn/student'
      path: '/student'
      fullPath: '/learn/student'
      preLoaderRoute: typeof LearnStudentRouteImport
      parentRoute: typeof LearnRoute
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/rooms/book': {
      id: '/rooms/book'
      path: '/book'
      fullPath: '/rooms/book'
      preLoaderRoute: typeof RoomsBookRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/rooms/reservations': {
      id: '/rooms/reservations'
      path: '/reservations'
      fullPath: '/rooms/reservations'
      preLoaderRoute: typeof RoomsReservationsRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/rooms/structure': {
      id: '/rooms/structure'
      path: '/structure'
      fullPath: '/rooms/structure'
      preLoaderRoute: typeof RoomsStructureRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/activities': {
      id: '/student/activities'
      path: '/activities'
      fullPath: '/student/activities'
      preLoaderRoute: typeof StudentActivitiesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/disciplines': {
      id: '/student/disciplines'
      path: '/disciplines'
      fullPath: '/student/disciplines'
      preLoaderRoute: typeof StudentDisciplinesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/documents': {
      id: '/student/documents'
      path: '/documents'
      fullPath: '/student/documents'
      preLoaderRoute: typeof StudentDocumentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/finance': {
      id: '/student/finance'
      path: '/finance'
      fullPath: '/student/finance'
      preLoaderRoute: typeof StudentFinanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/history': {
      id: '/student/history'
      path: '/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof StudentHistoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/reservations': {
      id: '/student/reservations'
      path: '/reservations'
      fullPath: '/student/reservations'
      preLoaderRoute: typeof StudentReservationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/tickets': {
      id: '/student/tickets'
      path: '/tickets'
      fullPath: '/student/tickets'
      preLoaderRoute: typeof StudentTicketsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/boost/courses/$id': {
      id: '/boost/courses/$id'
      path: '/courses/$id'
      fullPath: '/boost/courses/$id'
      preLoaderRoute: typeof BoostCoursesIdRouteImport
      parentRoute: typeof BoostRoute
    }
    '/desk/categories/': {
      id: '/desk/categories/'
      path: '/'
      fullPath: '/desk/categories/'
      preLoaderRoute: typeof DeskCategoriesIndexRouteImport
      parentRoute: typeof DeskCategoriesRoute
    }
    '/desk/categories/$id': {
      id: '/desk/categories/$id'
      path: '/$id'
      fullPath: '/desk/categories/$id'
      preLoaderRoute: typeof DeskCategoriesIdRouteImport
      parentRoute: typeof DeskCategoriesRoute
    }
    '/desk/tickets/$id': {
      id: '/desk/tickets/$id'
      path: '/$id'
      fullPath: '/desk/tickets/$id'
      preLoaderRoute: typeof DeskTicketsIdRouteImport
      parentRoute: typeof DeskTicketsRoute
    }
    '/learn/activities/$id': {
      id: '/learn/activities/$id'
      path: '/activities/$id'
      fullPath: '/learn/activities/$id'
      preLoaderRoute: typeof LearnActivitiesIdRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface AcademyRouteChildren {
  AcademyAttendanceRoute: typeof AcademyAttendanceRoute
  AcademyGradesRoute: typeof AcademyGradesRoute
  AcademyManageRoute: typeof AcademyManageRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyAttendanceRoute: AcademyAttendanceRoute,
  AcademyGradesRoute: AcademyGradesRoute,
  AcademyManageRoute: AcademyManageRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface AssetsRouteChildren {
  AssetsInventoryRoute: typeof AssetsInventoryRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsInventoryRoute: AssetsInventoryRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface BoostRouteChildren {
  BoostIndexRoute: typeof BoostIndexRoute
  BoostCoursesIdRoute: typeof BoostCoursesIdRoute
}

const BoostRouteChildren: BoostRouteChildren = {
  BoostIndexRoute: BoostIndexRoute,
  BoostCoursesIdRoute: BoostCoursesIdRoute,
}

const BoostRouteWithChildren = BoostRoute._addFileChildren(BoostRouteChildren)

interface DeskCategoriesRouteChildren {
  DeskCategoriesIdRoute: typeof DeskCategoriesIdRoute
  DeskCategoriesIndexRoute: typeof DeskCategoriesIndexRoute
}

const DeskCategoriesRouteChildren: DeskCategoriesRouteChildren = {
  DeskCategoriesIdRoute: DeskCategoriesIdRoute,
  DeskCategoriesIndexRoute: DeskCategoriesIndexRoute,
}

const DeskCategoriesRouteWithChildren = DeskCategoriesRoute._addFileChildren(
  DeskCategoriesRouteChildren,
)

interface DeskTicketsRouteChildren {
  DeskTicketsIdRoute: typeof DeskTicketsIdRoute
}

const DeskTicketsRouteChildren: DeskTicketsRouteChildren = {
  DeskTicketsIdRoute: DeskTicketsIdRoute,
}

const DeskTicketsRouteWithChildren = DeskTicketsRoute._addFileChildren(
  DeskTicketsRouteChildren,
)

interface DeskRouteChildren {
  DeskCategoriesRoute: typeof DeskCategoriesRouteWithChildren
  DeskTeamRoute: typeof DeskTeamRoute
  DeskTicketsRoute: typeof DeskTicketsRouteWithChildren
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskCategoriesRoute: DeskCategoriesRouteWithChildren,
  DeskTeamRoute: DeskTeamRoute,
  DeskTicketsRoute: DeskTicketsRouteWithChildren,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface FinanceRouteChildren {
  FinanceBoletosRoute: typeof FinanceBoletosRoute
  FinanceChargesRoute: typeof FinanceChargesRoute
  FinanceDiscountsRoute: typeof FinanceDiscountsRoute
  FinanceManageRoute: typeof FinanceManageRoute
  FinanceNfeRoute: typeof FinanceNfeRoute
  FinanceProductsRoute: typeof FinanceProductsRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  FinanceServicesRoute: typeof FinanceServicesRoute
  FinanceSettingsRoute: typeof FinanceSettingsRoute
  FinanceTuitionsRoute: typeof FinanceTuitionsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceBoletosRoute: FinanceBoletosRoute,
  FinanceChargesRoute: FinanceChargesRoute,
  FinanceDiscountsRoute: FinanceDiscountsRoute,
  FinanceManageRoute: FinanceManageRoute,
  FinanceNfeRoute: FinanceNfeRoute,
  FinanceProductsRoute: FinanceProductsRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  FinanceServicesRoute: FinanceServicesRoute,
  FinanceSettingsRoute: FinanceSettingsRoute,
  FinanceTuitionsRoute: FinanceTuitionsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface HubRouteChildren {
  HubAcessosRoute: typeof HubAcessosRoute
  HubSetoresRoute: typeof HubSetoresRoute
  HubUsuariosRoute: typeof HubUsuariosRoute
  HubIndexRoute: typeof HubIndexRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubAcessosRoute: HubAcessosRoute,
  HubSetoresRoute: HubSetoresRoute,
  HubUsuariosRoute: HubUsuariosRoute,
  HubIndexRoute: HubIndexRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

interface LearnRouteChildren {
  LearnClassesRoute: typeof LearnClassesRoute
  LearnStudentRoute: typeof LearnStudentRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnActivitiesIdRoute: typeof LearnActivitiesIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnClassesRoute: LearnClassesRoute,
  LearnStudentRoute: LearnStudentRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnActivitiesIdRoute: LearnActivitiesIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface RoomsRouteChildren {
  RoomsBookRoute: typeof RoomsBookRoute
  RoomsReservationsRoute: typeof RoomsReservationsRoute
  RoomsStructureRoute: typeof RoomsStructureRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsBookRoute: RoomsBookRoute,
  RoomsReservationsRoute: RoomsReservationsRoute,
  RoomsStructureRoute: RoomsStructureRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

interface StudentRouteChildren {
  StudentActivitiesRoute: typeof StudentActivitiesRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDisciplinesRoute: typeof StudentDisciplinesRoute
  StudentDocumentsRoute: typeof StudentDocumentsRoute
  StudentFinanceRoute: typeof StudentFinanceRoute
  StudentGradesRoute: typeof StudentGradesRoute
  StudentHistoryRoute: typeof StudentHistoryRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentReservationsRoute: typeof StudentReservationsRoute
  StudentTicketsRoute: typeof StudentTicketsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentActivitiesRoute: StudentActivitiesRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentCalendarRoute: StudentCalendarRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDisciplinesRoute: StudentDisciplinesRoute,
  StudentDocumentsRoute: StudentDocumentsRoute,
  StudentFinanceRoute: StudentFinanceRoute,
  StudentGradesRoute: StudentGradesRoute,
  StudentHistoryRoute: StudentHistoryRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentReservationsRoute: StudentReservationsRoute,
  StudentTicketsRoute: StudentTicketsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AssetsRoute: AssetsRouteWithChildren,
  BoostRoute: BoostRouteWithChildren,
  DeskRoute: DeskRouteWithChildren,
  FinanceRoute: FinanceRouteWithChildren,
  HubRoute: HubRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
